version: '3'
services:
  hp-server: 
    build:
      context: .
      dockerfile: docker-nginx
    ports:
      - "8006:80"
    volumes:
      - "./dist:/var/www/html"
      - "./conf.d/default.conf:/etc/nginx/conf.d/default.conf"

